---
name: CI/CD Pipeline
on:
  workflow_dispatch: 

  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run_test: true

  test:
    needs: build
    uses: ./.github/workflows/reusable-docker.yml
    secrets: inherit
    with:
      image_name: three-tier-app
      image_tag: latest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Deploy
        run: echo "Deploying Image - ${{ needs.test.outputs.image_url }} to Production"
      
